spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviebookingapp
    username: root
    password: Pro1234$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: aBHjrujfbs@$#kmndjd12kkfnrkrnrkms45DNKNNC
  expiration: 36000000